version: 0.2
env:
  parameter-store:
    # Requires that you have a secure string in AWS Systems Manager Parameter Store
    # called "snykAuthToken" with your Snyk token.
    SNYK_TOKEN: "snykAuthToken"
phases:
  install:
    commands:
      - npm install -g snyk
      - node -v
      - yarn
      - yarn global add serverless@3.27.0
      - sls -v
      - cd layers/lib/nodejs
      - yarn --prod
      - cd ../../..
      - cd layers/db/nodejs
      - yarn --prod
      - cd ../../..
      - run_and_check_command() { snyk test --on-fail=all; if [ $? -ne 0 ]; then snyk monitor --org=f7b6de39-69ab-4df6-a882-9b9b8a7f332e; exit 1; else snyk monitor --org=f7b6de39-69ab-4df6-a882-9b9b8a7f332e; fi }; run_and_check_command
      - echo $?
  build:
    commands:
      - echo $Stage
      - serverless deploy --stage $Stage --max-concurrency 10
