version: 0.2
phases:
  install:
    commands:
      - node -v
      - yarn
      - yarn global add serverless@3.25.0
      - sls -v
      - cd layers/lib/nodejs
      - ls
      - yarn --prod
      - cd ../../..
      - ls
      - cd layers/db/nodejs
      - ls
      - yarn --prod
      - cd ../../..
      - ls
      - find . -type f -name "serverless*.ts" -exec sed -i 's/@@stage@@/{$Stage}/g' {} +
  build:
    commands:
      - echo $Stage
      - serverless deploy --stage $Stage --max-concurrency 5