version: 0.2

env:
  parameter-store:
    # Requires that you have a secure string in AWS Systems Manager Parameter Store
    # called "snykAuthToken" with your Snyk token.
    SNYK_TOKEN: "snykAuthToken"
   # SNYK_ORG: "TargetOrg"

phases:
  install:
    commands:
      - npm install -g snyk
      - npm install
 
     
  build:
    on-failure: CONTINUE
    commands:
      - snyk code test 
