enum Resorts {
    
    SUN_PALACE = "ZHSP",
    MOON_PALACE_THE_GRANDCANCUN = "ZMGR",
    MOON_PALACE_CANCUN_NIZUC = "ZMNI",
    MOON_PALACE_CANCUN_SUNRISE = "ZMSU",
    BEACH_PALACE = "ZHBP",
    ISLA_MUJERES_PALACE = "ZHIM",
    LE_BLANC_SPA_RESORT_CANCUN = "ZHLB",
    PLAYACAR_PALACE = "ZRPL",
    COZUMEL_PALACE = "ZRCZ",
    MOON_PALACE_JAMAICA = "ZCJG",
    LE_BLANC_SPA_RESORT_LOS_CABOS = "ZPLB",
    CEDIS_PALACE_RESORTS = "CDS",
    MOON_PALACE_PUNTA_CANA = "ZCMPPC",

}

export default  Resorts;