export default {
  DBConnectionManager: Symbol.for('DBConnectionManager'),
  DBConnectionHelperTypeORM: Symbol.for('DBConnectionHelperTypeORM'),
  DBConnectionOfflineHelper: Symbol.for('DBConnectionOfflineHelper'),
  DBConnectionHelperFactory: Symbol.for('DBConnectionHelperFactory'),
  SecretsManager: Symbol.for('SecretsManager'),
  APIGatewayResultMapperService: Symbol.for('APIGatewayResultMapperService'),
  ApiGatewayGetAdapter: Symbol.for('ApiGatewayGetAdapter'),
  ApiGatewayPostAdapter: Symbol.for('ApiGatewayPostAdapter'),
  ApiGatewayGetUseCase: Symbol.for('ApiGatewayGetUseCase'),
  ApiGatewayPostUseCase: Symbol.for('ApiGatewayPostUseCase'),
  CoupleFindPaginatedRepository: Symbol.for('CoupleFindPaginatedRepository'),
  PersonMapper: Symbol.for('PersonMapper'),
  CoupleMapper: Symbol.for('CoupleMapper'),
  PaginationMapperService: Symbol.for('PaginationMapperService'),
  CoupleCreateOneRepository: Symbol.for('CoupleCreateOneRepository'),
  PersonCreateOneRepository: Symbol.for('PersonCreateOneRepository'),
  PropertyGetAdapter: Symbol.for('PropertyGetAdapter'),
  PropertyGetUseCase: Symbol.for('PropertyGetUseCase'),
  PropertyFindRepository: Symbol.for('PropertyFindRepository'),
  InvalidCoupleAdapter: Symbol.for('InvalidCoupleAdapter')
}